import { FaWhatsapp } from "react-icons/fa";

import { GeistSans } from "geist/font/sans";
import Hero from "../_components/Hero";
import TransitionSection from "../_components/TransitionSection";
import Benefits from "../_components/Benefits";
import Table from "../_components/Table";
import FormCTA from "../_components/FormCTA";
import FAQ from "../_components/FAQ";
import { MainNavBar } from "../../../components/structure/nav-structure";
export const metadata = {
  title: "Your Count",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="bg-[#171326]">
      <Hero />
      <section
        className="w-full overflow-hidden mt-[150px]  py-[50px]"
        id="hero"
      >
        <div className="max-container padding-container  flex flex-col flexCenter gap-10  ">
          <MainNavBar />

          {children}
        </div>
      </section>
      <TransitionSection />
      <Benefits />
      <Table />
      <FormCTA />
      <FAQ />
    </div>
  );
}
