import { FaWhatsapp } from "react-icons/fa";
import "./globals.css";

import { GeistSans } from "geist/font/sans";
import Footer from "../components/Footer";
import Link from "next/link";
import NavBar from "../components/Navbar";
import { Sora } from "next/font/google";
export const metadata = {
  title: "Your Count",
  description: "Generated by create next app",
};

const sora = Sora({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sora.className} scroll-smooth`}>
      <body>
        <NavBar />
        <main>{children}</main>
        <Footer />
        <Link href={"/"}>
          <div className="fixed bottom-5 right-5 p-3 rounded-[20px] bg-[#45d48f] ">
            <FaWhatsapp size={40} color="#fff" />
          </div>
        </Link>
      </body>
    </html>
  );
}
